//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlutensizYasam.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlutensizYasam.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1613681330_59_p_fon_dlya_prezentatsii_pravilnoe_pitanie_69 {
            get {
                object obj = ResourceManager.GetObject("1613681330_59-p-fon-dlya-prezentatsii-pravilnoe-pitanie-69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _165_1650983_housing_financial_options_level_green_icon_png {
            get {
                object obj = ResourceManager.GetObject("165-1650983_housing-financial-options-level-green-icon-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _165_1650983_housing_financial_options_level_green_icon_png1 {
            get {
                object obj = ResourceManager.GetObject("165-1650983_housing-financial-options-level-green-icon-png1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _165_1650983_housing_financial_options_level_green_icon_png2 {
            get {
                object obj = ResourceManager.GetObject("165-1650983_housing-financial-options-level-green-icon-png2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _165_1650983_housing_financial_options_level_green_icon_png3 {
            get {
                object obj = ResourceManager.GetObject("165-1650983_housing-financial-options-level-green-icon-png3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _168_1686888_diet_icon_3d {
            get {
                object obj = ResourceManager.GetObject("168-1686888_diet-icon-3d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _168_1686888_diet_icon_3d1 {
            get {
                object obj = ResourceManager.GetObject("168-1686888_diet-icon-3d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3f2ae8fc132bafca49a23144a28dbfcb {
            get {
                object obj = ResourceManager.GetObject("3f2ae8fc132bafca49a23144a28dbfcb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3f2ae8fc132bafca49a23144a28dbfcb1 {
            get {
                object obj = ResourceManager.GetObject("3f2ae8fc132bafca49a23144a28dbfcb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4984467 {
            get {
                object obj = ResourceManager.GetObject("4984467", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contactno_ {
            get {
                object obj = ResourceManager.GetObject("contactno.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_logo_icon_24 {
            get {
                object obj = ResourceManager.GetObject("home-logo-icon-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_gluten_free_diet_celiac_disease_essential_gluten_f_blog_functional_medicine_supplements_5c51e63cf2cfb3_5941625015488712289946 {
            get {
                object obj = ResourceManager.GetObject("kisspng-gluten-free-diet-celiac-disease-essential-gluten-f-blog-functional-medici" +
                        "ne-supplements-5c51e63cf2cfb3.5941625015488712289946", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_logo_font_brand_clip_art_united_kingdom_5cbd4af80bec99_4733100815559093680489 {
            get {
                object obj = ResourceManager.GetObject("kisspng-logo-font-brand-clip-art-united-kingdom-5cbd4af80bec99.473310081555909368" +
                        "0489", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_nutrition_health_dietitian_food_manzana_png_5b4b58c33017f9_750271291531664579197 {
            get {
                object obj = ResourceManager.GetObject("kisspng-nutrition-health-dietitian-food-manzana-png-5b4b58c33017f9.75027129153166" +
                        "4579197", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_water_services_symbol_clip_art_5ae4e724489716_2635628515249508202973 {
            get {
                object obj = ResourceManager.GetObject("kisspng-water-services-symbol-clip-art-5ae4e724489716.2635628515249508202973", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_water_services_symbol_clip_art_5ae4e7244897161 {
            get {
                object obj = ResourceManager.GetObject("kisspng-water-services-symbol-clip-art-5ae4e7244897161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kitchen_utensil_logo_rolling_pins_cook_png_favpng_7iwYTPCeD9U0hVRVbup0k4Xhf {
            get {
                object obj = ResourceManager.GetObject("kitchen-utensil-logo-rolling-pins-cook-png-favpng-7iwYTPCeD9U0hVRVbup0k4Xhf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_lunch_meal_breakfast_dinner_breakfast_food_text {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-lunch-meal-breakfast-dinner-breakfast-food-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_shopping_list_others_angle_text {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-shopping-list-others-angle-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_dieting_healthy_diet_food_obesity_health_angle_food {
            get {
                object obj = ResourceManager.GetObject("png-clipart-dieting-healthy-diet-food-obesity-health-angle-food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_drinking_water_logo_axalta_coating_systems_urine_test_leaf_service {
            get {
                object obj = ResourceManager.GetObject("png-clipart-drinking-water-logo-axalta-coating-systems-urine-test-leaf-service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_drinking_water_logo_axalta_coating_systems_urine_test_leaf_service1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-drinking-water-logo-axalta-coating-systems-urine-test-leaf-service1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_united_states_drinking_water_dentist_water_scarcity_glass_of_milk_glass_dentistry {
            get {
                object obj = ResourceManager.GetObject("png-clipart-united-states-drinking-water-dentist-water-scarcity-glass-of-milk-gla" +
                        "ss-dentistry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_black_person_symbol_art_computer_icons_user_profile_avatar_profile_heroes_profile_user_interface {
            get {
                object obj = ResourceManager.GetObject("png-transparent-black-person-symbol-art-computer-icons-user-profile-avatar-profil" +
                        "e-heroes-profile-user-interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_drinking_water_computer_icons_water_treatment_water_supply_network_peggy_s_blue_angle_service {
            get {
                object obj = ResourceManager.GetObject("png-transparent-drinking-water-computer-icons-water-treatment-water-supply-networ" +
                        "k-peggy-s-blue-angle-service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_drinking_water_computer_icons_water_treatment_water_supply_network_peggy_s_blue_angle_service2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-drinking-water-computer-icons-water-treatment-water-supply-networ" +
                        "k-peggy-s-blue-angle-service2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_water_logo_national_interest_market_montpellier_m_i_n_coriovallum_college_agua_television_blue_angle {
            get {
                object obj = ResourceManager.GetObject("png-transparent-water-logo-national-interest-market-montpellier-m-i-n-coriovallum" +
                        "-college-agua-television-blue-angle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_water_logo_national_interest_market_montpellier_m_i_n_coriovallum_college_agua_television_blue_angle1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-water-logo-national-interest-market-montpellier-m-i-n-coriovallum" +
                        "-college-agua-television-blue-angle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_water_logo_national_interest_market_montpellier_m_i_n_coriovallum_college_agua_television_blue_angle2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-water-logo-national-interest-market-montpellier-m-i-n-coriovallum" +
                        "-college-agua-television-blue-angle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_water_logo_national_interest_market_montpellier_m_i_n_coriovallum_college_agua_television_blue_angle3 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-water-logo-national-interest-market-montpellier-m-i-n-coriovallum" +
                        "-college-agua-television-blue-angle3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_water_logo_national_interest_market_montpellier_m_i_n_coriovallum_college_agua_television_blue_angle4 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-water-logo-national-interest-market-montpellier-m-i-n-coriovallum" +
                        "-college-agua-television-blue-angle4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen_1 {
            get {
                object obj = ResourceManager.GetObject("screen-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap su {
            get {
                object obj = ResourceManager.GetObject("su", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wheat_allergy_amber_icon_15413 {
            get {
                object obj = ResourceManager.GetObject("wheat-allergy-amber-icon_15413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wheat_allergy_amber_icon_154131 {
            get {
                object obj = ResourceManager.GetObject("wheat-allergy-amber-icon_154131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
